OUTPUT_DIR: output
LOG_DIR: 
DATA_DIR: 
CHECKPOINT_DIR: content
GPUS: (0, 1)
WORKERS: 4
PRINT_FREQ: 100
AUTO_RESUME: True
LABEL_PER_CLASS: 15
MODEL_PATH: SMAL/smal_CVPR2018.pkl
DATA_PATH: SMAL/smal_CVPR2018_data.pkl
GEN_DIR: SMAL
CUDNN: BENCHMARK: True
DETERMINISTIC: False
ENABLED: True
MODEL: BOTTLENECK_SIZE: 2048
CHANNEL_PER_GROUP: 16
EXTRA:
  FINAL_CONV_KERNEL: 1
  PRETRAINED_LAYERS: ['conv1', 'bn1', 'conv2', 'bn2', 'layer1', 'transition1', 'stage2', 'transition2', 'stage3', 'transition3', 'stage4']
  STAGE2:
    BLOCK: BASIC
    FUSE_METHOD: SUM
    NUM_BLOCKS: [4, 4]
    NUM_BRANCHES: 2
    NUM_CHANNELS: [32, 64]
    NUM_MODULES: 1
  STAGE3:
    BLOCK: BASIC
    FUSE_METHOD: SUM
    NUM_BLOCKS: [4, 4, 4]
    NUM_BRANCHES: 3
    NUM_CHANNELS: [32, 64, 128]
    NUM_MODULES: 4
  STAGE4:
    BLOCK: BASIC
    FUSE_METHOD: SUM
    NUM_BLOCKS: [4, 4, 4, 4]
    NUM_BRANCHES: 4
    NUM_CHANNELS: [32, 64, 128, 256]
    NUM_MODULES: 3
HEATMAP_SIZE: [64, 64]
IMAGE_SIZE: [256, 256]
INIT_WEIGHTS: True
NAME: pose_hrnet
NUM_JOINTS: 17
NUM_KPS: 28
NZ_FEAT: 1024
N_SHAPE_FEAT: 40
OPTIMIZATION: False
PRETRAINED: models/pytorch/imagenet/hrnet_w32-36af842e.pth
SIGMA: 2
TAG_PER_JOINT: True
TARGET_TYPE: gaussian
LOSS: USE_TARGET_WEIGHT: True
TRAIN: BATCH_SIZE_PER_GPU: 32
BEGIN_EPOCH: 0
END_EPOCH: 210
GAMMA1: 0.99
GAMMA2: 0
LR: 0.001
LR_FACTOR: 0.1
LR_STEP: [170, 200]
MOMENTUM: 0.9
NESTEROV: False
NUM_BETAS: 20
N_DATA_WORKERS: 4
OPTIMIZER: adam
SHUFFLE: True
WD: 0.0001
DATASET: COLOR_RGB: True
DATASET: animal3d
DATA_DIR: /media/lap16043/fe6895ab-3146-48c7-ba28-d1d7add169ce/Thesis/Datasets/animal3d-20240404T061206Z-001/animal3d
DATA_FORMAT: jpg
FLIP: True
NUM_JOINTS_HALF_BODY: 8
PROB_HALF_BODY: 0.3
ROOT: data/animalpose/
ROT_FACTOR: 40
SCALE_FACTOR: 0.5
SELECT_DATA: False
SMAL_MEAN_PARAMS: data/smpl_mean_params.npz
SUPERCATEGORY: ['Bovidae']
TEST_SET: test
TRAIN_SET: train
VAL_SET: val
TEST: BATCH_SIZE_PER_GPU: 32
BBOX_THRE: 1
COCO_BBOX_FILE: 
FLIP_TEST: True
IMAGE_THRE: 0
IN_VIS_THRE: 0.2
MODEL_FILE: 
NMS_THRE: 1
OKS_THRE: 0.9
POST_PROCESS: True
SHIFT_HEATMAP: True
USE_GT_BBOX: True
DEBUG: DEBUG: True
SAVE_BATCH_IMAGES_GT: True
SAVE_BATCH_IMAGES_PRED: True
SAVE_HEATMAPS_GT: True
SAVE_HEATMAPS_PRED: True
